// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opencensus/proto/agent/metrics/v1/metrics_service.proto

package io.opencensus.proto.agent.metrics.v1;

public final class MetricsServiceProto {
  private MetricsServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
