// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opencensus/proto/stats/v1/stats.proto

package io.opencensus.proto.stats.v1;

/**
 * <pre>
 * Describes a data point to be collected for a Measure.
 * </pre>
 *
 * Protobuf type {@code opencensus.proto.stats.v1.Measurement}
 */
public  final class Measurement extends
    com.google.protobuf.GeneratedMessageLite<
        Measurement, Measurement.Builder> implements
    // @@protoc_insertion_point(message_implements:opencensus.proto.stats.v1.Measurement)
    MeasurementOrBuilder {
  private Measurement() {
    tags_ = emptyProtobufList();
    measureName_ = "";
  }
  private int valueCase_ = 0;
  private java.lang.Object value_;
  public enum ValueCase {
    DOUBLE_VALUE(3),
    INT_VALUE(4),
    VALUE_NOT_SET(0);
    private final int value;
    private ValueCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ValueCase valueOf(int value) {
      return forNumber(value);
    }

    public static ValueCase forNumber(int value) {
      switch (value) {
        case 3: return DOUBLE_VALUE;
        case 4: return INT_VALUE;
        case 0: return VALUE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  @java.lang.Override
  public ValueCase
  getValueCase() {
    return ValueCase.forNumber(
        valueCase_);
  }

  private void clearValue() {
    valueCase_ = 0;
    value_ = null;
  }

  public static final int TAGS_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<io.opencensus.proto.stats.v1.Tag> tags_;
  /**
   * <code>repeated .opencensus.proto.stats.v1.Tag tags = 1;</code>
   */
  @java.lang.Override
  public java.util.List<io.opencensus.proto.stats.v1.Tag> getTagsList() {
    return tags_;
  }
  /**
   * <code>repeated .opencensus.proto.stats.v1.Tag tags = 1;</code>
   */
  public java.util.List<? extends io.opencensus.proto.stats.v1.TagOrBuilder> 
      getTagsOrBuilderList() {
    return tags_;
  }
  /**
   * <code>repeated .opencensus.proto.stats.v1.Tag tags = 1;</code>
   */
  @java.lang.Override
  public int getTagsCount() {
    return tags_.size();
  }
  /**
   * <code>repeated .opencensus.proto.stats.v1.Tag tags = 1;</code>
   */
  @java.lang.Override
  public io.opencensus.proto.stats.v1.Tag getTags(int index) {
    return tags_.get(index);
  }
  /**
   * <code>repeated .opencensus.proto.stats.v1.Tag tags = 1;</code>
   */
  public io.opencensus.proto.stats.v1.TagOrBuilder getTagsOrBuilder(
      int index) {
    return tags_.get(index);
  }
  private void ensureTagsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<io.opencensus.proto.stats.v1.Tag> tmp = tags_;
    if (!tmp.isModifiable()) {
      tags_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .opencensus.proto.stats.v1.Tag tags = 1;</code>
   */
  private void setTags(
      int index, io.opencensus.proto.stats.v1.Tag value) {
    value.getClass();
  ensureTagsIsMutable();
    tags_.set(index, value);
  }
  /**
   * <code>repeated .opencensus.proto.stats.v1.Tag tags = 1;</code>
   */
  private void addTags(io.opencensus.proto.stats.v1.Tag value) {
    value.getClass();
  ensureTagsIsMutable();
    tags_.add(value);
  }
  /**
   * <code>repeated .opencensus.proto.stats.v1.Tag tags = 1;</code>
   */
  private void addTags(
      int index, io.opencensus.proto.stats.v1.Tag value) {
    value.getClass();
  ensureTagsIsMutable();
    tags_.add(index, value);
  }
  /**
   * <code>repeated .opencensus.proto.stats.v1.Tag tags = 1;</code>
   */
  private void addAllTags(
      java.lang.Iterable<? extends io.opencensus.proto.stats.v1.Tag> values) {
    ensureTagsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, tags_);
  }
  /**
   * <code>repeated .opencensus.proto.stats.v1.Tag tags = 1;</code>
   */
  private void clearTags() {
    tags_ = emptyProtobufList();
  }
  /**
   * <code>repeated .opencensus.proto.stats.v1.Tag tags = 1;</code>
   */
  private void removeTags(int index) {
    ensureTagsIsMutable();
    tags_.remove(index);
  }

  public static final int MEASURE_NAME_FIELD_NUMBER = 2;
  private java.lang.String measureName_;
  /**
   * <pre>
   * The name of the measure to which the value is applied.
   * </pre>
   *
   * <code>string measure_name = 2;</code>
   * @return The measureName.
   */
  @java.lang.Override
  public java.lang.String getMeasureName() {
    return measureName_;
  }
  /**
   * <pre>
   * The name of the measure to which the value is applied.
   * </pre>
   *
   * <code>string measure_name = 2;</code>
   * @return The bytes for measureName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMeasureNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(measureName_);
  }
  /**
   * <pre>
   * The name of the measure to which the value is applied.
   * </pre>
   *
   * <code>string measure_name = 2;</code>
   * @param value The measureName to set.
   */
  private void setMeasureName(
      java.lang.String value) {
    value.getClass();
  
    measureName_ = value;
  }
  /**
   * <pre>
   * The name of the measure to which the value is applied.
   * </pre>
   *
   * <code>string measure_name = 2;</code>
   */
  private void clearMeasureName() {
    
    measureName_ = getDefaultInstance().getMeasureName();
  }
  /**
   * <pre>
   * The name of the measure to which the value is applied.
   * </pre>
   *
   * <code>string measure_name = 2;</code>
   * @param value The bytes for measureName to set.
   */
  private void setMeasureNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    measureName_ = value.toStringUtf8();
    
  }

  public static final int DOUBLE_VALUE_FIELD_NUMBER = 3;
  /**
   * <code>double double_value = 3;</code>
   * @return The doubleValue.
   */
  @java.lang.Override
  public double getDoubleValue() {
    if (valueCase_ == 3) {
      return (java.lang.Double) value_;
    }
    return 0D;
  }
  /**
   * <code>double double_value = 3;</code>
   * @param value The doubleValue to set.
   */
  private void setDoubleValue(double value) {
    valueCase_ = 3;
    value_ = value;
  }
  /**
   * <code>double double_value = 3;</code>
   */
  private void clearDoubleValue() {
    if (valueCase_ == 3) {
      valueCase_ = 0;
      value_ = null;
    }
  }

  public static final int INT_VALUE_FIELD_NUMBER = 4;
  /**
   * <code>int64 int_value = 4;</code>
   * @return The intValue.
   */
  @java.lang.Override
  public long getIntValue() {
    if (valueCase_ == 4) {
      return (java.lang.Long) value_;
    }
    return 0L;
  }
  /**
   * <code>int64 int_value = 4;</code>
   * @param value The intValue to set.
   */
  private void setIntValue(long value) {
    valueCase_ = 4;
    value_ = value;
  }
  /**
   * <code>int64 int_value = 4;</code>
   */
  private void clearIntValue() {
    if (valueCase_ == 4) {
      valueCase_ = 0;
      value_ = null;
    }
  }

  public static final int TIME_FIELD_NUMBER = 5;
  private com.google.protobuf.Timestamp time_;
  /**
   * <pre>
   * The time when this measurement was recorded. If the implementation uses a async buffer to
   * record measurements this may be the time when the measurement was read from the buffer.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp time = 5;</code>
   */
  @java.lang.Override
  public boolean hasTime() {
    return time_ != null;
  }
  /**
   * <pre>
   * The time when this measurement was recorded. If the implementation uses a async buffer to
   * record measurements this may be the time when the measurement was read from the buffer.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp time = 5;</code>
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getTime() {
    return time_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : time_;
  }
  /**
   * <pre>
   * The time when this measurement was recorded. If the implementation uses a async buffer to
   * record measurements this may be the time when the measurement was read from the buffer.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp time = 5;</code>
   */
  private void setTime(com.google.protobuf.Timestamp value) {
    value.getClass();
  time_ = value;
    
    }
  /**
   * <pre>
   * The time when this measurement was recorded. If the implementation uses a async buffer to
   * record measurements this may be the time when the measurement was read from the buffer.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp time = 5;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeTime(com.google.protobuf.Timestamp value) {
    value.getClass();
  if (time_ != null &&
        time_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
      time_ =
        com.google.protobuf.Timestamp.newBuilder(time_).mergeFrom(value).buildPartial();
    } else {
      time_ = value;
    }
    
  }
  /**
   * <pre>
   * The time when this measurement was recorded. If the implementation uses a async buffer to
   * record measurements this may be the time when the measurement was read from the buffer.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp time = 5;</code>
   */
  private void clearTime() {  time_ = null;
    
  }

  public static io.opencensus.proto.stats.v1.Measurement parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.opencensus.proto.stats.v1.Measurement parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.opencensus.proto.stats.v1.Measurement parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.opencensus.proto.stats.v1.Measurement parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.opencensus.proto.stats.v1.Measurement parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.opencensus.proto.stats.v1.Measurement parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.opencensus.proto.stats.v1.Measurement parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.opencensus.proto.stats.v1.Measurement parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.opencensus.proto.stats.v1.Measurement parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static io.opencensus.proto.stats.v1.Measurement parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.opencensus.proto.stats.v1.Measurement parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.opencensus.proto.stats.v1.Measurement parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.opencensus.proto.stats.v1.Measurement prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Describes a data point to be collected for a Measure.
   * </pre>
   *
   * Protobuf type {@code opencensus.proto.stats.v1.Measurement}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.opencensus.proto.stats.v1.Measurement, Builder> implements
      // @@protoc_insertion_point(builder_implements:opencensus.proto.stats.v1.Measurement)
      io.opencensus.proto.stats.v1.MeasurementOrBuilder {
    // Construct using io.opencensus.proto.stats.v1.Measurement.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    @java.lang.Override
    public ValueCase
        getValueCase() {
      return instance.getValueCase();
    }

    public Builder clearValue() {
      copyOnWrite();
      instance.clearValue();
      return this;
    }


    /**
     * <code>repeated .opencensus.proto.stats.v1.Tag tags = 1;</code>
     */
    @java.lang.Override
    public java.util.List<io.opencensus.proto.stats.v1.Tag> getTagsList() {
      return java.util.Collections.unmodifiableList(
          instance.getTagsList());
    }
    /**
     * <code>repeated .opencensus.proto.stats.v1.Tag tags = 1;</code>
     */
    @java.lang.Override
    public int getTagsCount() {
      return instance.getTagsCount();
    }/**
     * <code>repeated .opencensus.proto.stats.v1.Tag tags = 1;</code>
     */
    @java.lang.Override
    public io.opencensus.proto.stats.v1.Tag getTags(int index) {
      return instance.getTags(index);
    }
    /**
     * <code>repeated .opencensus.proto.stats.v1.Tag tags = 1;</code>
     */
    public Builder setTags(
        int index, io.opencensus.proto.stats.v1.Tag value) {
      copyOnWrite();
      instance.setTags(index, value);
      return this;
    }
    /**
     * <code>repeated .opencensus.proto.stats.v1.Tag tags = 1;</code>
     */
    public Builder setTags(
        int index, io.opencensus.proto.stats.v1.Tag.Builder builderForValue) {
      copyOnWrite();
      instance.setTags(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .opencensus.proto.stats.v1.Tag tags = 1;</code>
     */
    public Builder addTags(io.opencensus.proto.stats.v1.Tag value) {
      copyOnWrite();
      instance.addTags(value);
      return this;
    }
    /**
     * <code>repeated .opencensus.proto.stats.v1.Tag tags = 1;</code>
     */
    public Builder addTags(
        int index, io.opencensus.proto.stats.v1.Tag value) {
      copyOnWrite();
      instance.addTags(index, value);
      return this;
    }
    /**
     * <code>repeated .opencensus.proto.stats.v1.Tag tags = 1;</code>
     */
    public Builder addTags(
        io.opencensus.proto.stats.v1.Tag.Builder builderForValue) {
      copyOnWrite();
      instance.addTags(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .opencensus.proto.stats.v1.Tag tags = 1;</code>
     */
    public Builder addTags(
        int index, io.opencensus.proto.stats.v1.Tag.Builder builderForValue) {
      copyOnWrite();
      instance.addTags(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .opencensus.proto.stats.v1.Tag tags = 1;</code>
     */
    public Builder addAllTags(
        java.lang.Iterable<? extends io.opencensus.proto.stats.v1.Tag> values) {
      copyOnWrite();
      instance.addAllTags(values);
      return this;
    }
    /**
     * <code>repeated .opencensus.proto.stats.v1.Tag tags = 1;</code>
     */
    public Builder clearTags() {
      copyOnWrite();
      instance.clearTags();
      return this;
    }
    /**
     * <code>repeated .opencensus.proto.stats.v1.Tag tags = 1;</code>
     */
    public Builder removeTags(int index) {
      copyOnWrite();
      instance.removeTags(index);
      return this;
    }

    /**
     * <pre>
     * The name of the measure to which the value is applied.
     * </pre>
     *
     * <code>string measure_name = 2;</code>
     * @return The measureName.
     */
    @java.lang.Override
    public java.lang.String getMeasureName() {
      return instance.getMeasureName();
    }
    /**
     * <pre>
     * The name of the measure to which the value is applied.
     * </pre>
     *
     * <code>string measure_name = 2;</code>
     * @return The bytes for measureName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMeasureNameBytes() {
      return instance.getMeasureNameBytes();
    }
    /**
     * <pre>
     * The name of the measure to which the value is applied.
     * </pre>
     *
     * <code>string measure_name = 2;</code>
     * @param value The measureName to set.
     * @return This builder for chaining.
     */
    public Builder setMeasureName(
        java.lang.String value) {
      copyOnWrite();
      instance.setMeasureName(value);
      return this;
    }
    /**
     * <pre>
     * The name of the measure to which the value is applied.
     * </pre>
     *
     * <code>string measure_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMeasureName() {
      copyOnWrite();
      instance.clearMeasureName();
      return this;
    }
    /**
     * <pre>
     * The name of the measure to which the value is applied.
     * </pre>
     *
     * <code>string measure_name = 2;</code>
     * @param value The bytes for measureName to set.
     * @return This builder for chaining.
     */
    public Builder setMeasureNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMeasureNameBytes(value);
      return this;
    }

    /**
     * <code>double double_value = 3;</code>
     * @return The doubleValue.
     */
    @java.lang.Override
    public double getDoubleValue() {
      return instance.getDoubleValue();
    }
    /**
     * <code>double double_value = 3;</code>
     * @param value The doubleValue to set.
     * @return This builder for chaining.
     */
    public Builder setDoubleValue(double value) {
      copyOnWrite();
      instance.setDoubleValue(value);
      return this;
    }
    /**
     * <code>double double_value = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDoubleValue() {
      copyOnWrite();
      instance.clearDoubleValue();
      return this;
    }

    /**
     * <code>int64 int_value = 4;</code>
     * @return The intValue.
     */
    @java.lang.Override
    public long getIntValue() {
      return instance.getIntValue();
    }
    /**
     * <code>int64 int_value = 4;</code>
     * @param value The intValue to set.
     * @return This builder for chaining.
     */
    public Builder setIntValue(long value) {
      copyOnWrite();
      instance.setIntValue(value);
      return this;
    }
    /**
     * <code>int64 int_value = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearIntValue() {
      copyOnWrite();
      instance.clearIntValue();
      return this;
    }

    /**
     * <pre>
     * The time when this measurement was recorded. If the implementation uses a async buffer to
     * record measurements this may be the time when the measurement was read from the buffer.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp time = 5;</code>
     */
    @java.lang.Override
    public boolean hasTime() {
      return instance.hasTime();
    }
    /**
     * <pre>
     * The time when this measurement was recorded. If the implementation uses a async buffer to
     * record measurements this may be the time when the measurement was read from the buffer.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp time = 5;</code>
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getTime() {
      return instance.getTime();
    }
    /**
     * <pre>
     * The time when this measurement was recorded. If the implementation uses a async buffer to
     * record measurements this may be the time when the measurement was read from the buffer.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp time = 5;</code>
     */
    public Builder setTime(com.google.protobuf.Timestamp value) {
      copyOnWrite();
      instance.setTime(value);
      return this;
      }
    /**
     * <pre>
     * The time when this measurement was recorded. If the implementation uses a async buffer to
     * record measurements this may be the time when the measurement was read from the buffer.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp time = 5;</code>
     */
    public Builder setTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      copyOnWrite();
      instance.setTime(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * The time when this measurement was recorded. If the implementation uses a async buffer to
     * record measurements this may be the time when the measurement was read from the buffer.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp time = 5;</code>
     */
    public Builder mergeTime(com.google.protobuf.Timestamp value) {
      copyOnWrite();
      instance.mergeTime(value);
      return this;
    }
    /**
     * <pre>
     * The time when this measurement was recorded. If the implementation uses a async buffer to
     * record measurements this may be the time when the measurement was read from the buffer.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp time = 5;</code>
     */
    public Builder clearTime() {  copyOnWrite();
      instance.clearTime();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:opencensus.proto.stats.v1.Measurement)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.opencensus.proto.stats.v1.Measurement();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "value_",
            "valueCase_",
            "tags_",
            io.opencensus.proto.stats.v1.Tag.class,
            "measureName_",
            "time_",
          };
          java.lang.String info =
              "\u0000\u0005\u0001\u0000\u0001\u0005\u0005\u0000\u0001\u0000\u0001\u001b\u0002\u0208" +
              "\u00033\u0000\u00045\u0000\u0005\t";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.opencensus.proto.stats.v1.Measurement> parser = PARSER;
        if (parser == null) {
          synchronized (io.opencensus.proto.stats.v1.Measurement.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.opencensus.proto.stats.v1.Measurement>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:opencensus.proto.stats.v1.Measurement)
  private static final io.opencensus.proto.stats.v1.Measurement DEFAULT_INSTANCE;
  static {
    Measurement defaultInstance = new Measurement();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Measurement.class, defaultInstance);
  }

  public static io.opencensus.proto.stats.v1.Measurement getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Measurement> PARSER;

  public static com.google.protobuf.Parser<Measurement> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

