// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opencensus/proto/metrics/v1/metrics.proto

package io.opencensus.proto.metrics.v1;

/**
 * Protobuf type {@code opencensus.proto.metrics.v1.LabelValue}
 */
public  final class LabelValue extends
    com.google.protobuf.GeneratedMessageLite<
        LabelValue, LabelValue.Builder> implements
    // @@protoc_insertion_point(message_implements:opencensus.proto.metrics.v1.LabelValue)
    LabelValueOrBuilder {
  private LabelValue() {
    value_ = "";
  }
  public static final int VALUE_FIELD_NUMBER = 1;
  private java.lang.String value_;
  /**
   * <pre>
   * The value for the label.
   * </pre>
   *
   * <code>string value = 1;</code>
   * @return The value.
   */
  @java.lang.Override
  public java.lang.String getValue() {
    return value_;
  }
  /**
   * <pre>
   * The value for the label.
   * </pre>
   *
   * <code>string value = 1;</code>
   * @return The bytes for value.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getValueBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(value_);
  }
  /**
   * <pre>
   * The value for the label.
   * </pre>
   *
   * <code>string value = 1;</code>
   * @param value The value to set.
   */
  private void setValue(
      java.lang.String value) {
    value.getClass();
  
    value_ = value;
  }
  /**
   * <pre>
   * The value for the label.
   * </pre>
   *
   * <code>string value = 1;</code>
   */
  private void clearValue() {
    
    value_ = getDefaultInstance().getValue();
  }
  /**
   * <pre>
   * The value for the label.
   * </pre>
   *
   * <code>string value = 1;</code>
   * @param value The bytes for value to set.
   */
  private void setValueBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    value_ = value.toStringUtf8();
    
  }

  public static final int HAS_VALUE_FIELD_NUMBER = 2;
  private boolean hasValue_;
  /**
   * <pre>
   * If false the value field is ignored and considered not set.
   * This is used to differentiate a missing label from an empty string.
   * </pre>
   *
   * <code>bool has_value = 2;</code>
   * @return The hasValue.
   */
  @java.lang.Override
  public boolean getHasValue() {
    return hasValue_;
  }
  /**
   * <pre>
   * If false the value field is ignored and considered not set.
   * This is used to differentiate a missing label from an empty string.
   * </pre>
   *
   * <code>bool has_value = 2;</code>
   * @param value The hasValue to set.
   */
  private void setHasValue(boolean value) {
    
    hasValue_ = value;
  }
  /**
   * <pre>
   * If false the value field is ignored and considered not set.
   * This is used to differentiate a missing label from an empty string.
   * </pre>
   *
   * <code>bool has_value = 2;</code>
   */
  private void clearHasValue() {
    
    hasValue_ = false;
  }

  public static io.opencensus.proto.metrics.v1.LabelValue parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.opencensus.proto.metrics.v1.LabelValue parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.opencensus.proto.metrics.v1.LabelValue parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.opencensus.proto.metrics.v1.LabelValue parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.opencensus.proto.metrics.v1.LabelValue parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.opencensus.proto.metrics.v1.LabelValue parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.opencensus.proto.metrics.v1.LabelValue parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.opencensus.proto.metrics.v1.LabelValue parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.opencensus.proto.metrics.v1.LabelValue parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static io.opencensus.proto.metrics.v1.LabelValue parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.opencensus.proto.metrics.v1.LabelValue parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.opencensus.proto.metrics.v1.LabelValue parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.opencensus.proto.metrics.v1.LabelValue prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code opencensus.proto.metrics.v1.LabelValue}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.opencensus.proto.metrics.v1.LabelValue, Builder> implements
      // @@protoc_insertion_point(builder_implements:opencensus.proto.metrics.v1.LabelValue)
      io.opencensus.proto.metrics.v1.LabelValueOrBuilder {
    // Construct using io.opencensus.proto.metrics.v1.LabelValue.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * The value for the label.
     * </pre>
     *
     * <code>string value = 1;</code>
     * @return The value.
     */
    @java.lang.Override
    public java.lang.String getValue() {
      return instance.getValue();
    }
    /**
     * <pre>
     * The value for the label.
     * </pre>
     *
     * <code>string value = 1;</code>
     * @return The bytes for value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValueBytes() {
      return instance.getValueBytes();
    }
    /**
     * <pre>
     * The value for the label.
     * </pre>
     *
     * <code>string value = 1;</code>
     * @param value The value to set.
     * @return This builder for chaining.
     */
    public Builder setValue(
        java.lang.String value) {
      copyOnWrite();
      instance.setValue(value);
      return this;
    }
    /**
     * <pre>
     * The value for the label.
     * </pre>
     *
     * <code>string value = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearValue() {
      copyOnWrite();
      instance.clearValue();
      return this;
    }
    /**
     * <pre>
     * The value for the label.
     * </pre>
     *
     * <code>string value = 1;</code>
     * @param value The bytes for value to set.
     * @return This builder for chaining.
     */
    public Builder setValueBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setValueBytes(value);
      return this;
    }

    /**
     * <pre>
     * If false the value field is ignored and considered not set.
     * This is used to differentiate a missing label from an empty string.
     * </pre>
     *
     * <code>bool has_value = 2;</code>
     * @return The hasValue.
     */
    @java.lang.Override
    public boolean getHasValue() {
      return instance.getHasValue();
    }
    /**
     * <pre>
     * If false the value field is ignored and considered not set.
     * This is used to differentiate a missing label from an empty string.
     * </pre>
     *
     * <code>bool has_value = 2;</code>
     * @param value The hasValue to set.
     * @return This builder for chaining.
     */
    public Builder setHasValue(boolean value) {
      copyOnWrite();
      instance.setHasValue(value);
      return this;
    }
    /**
     * <pre>
     * If false the value field is ignored and considered not set.
     * This is used to differentiate a missing label from an empty string.
     * </pre>
     *
     * <code>bool has_value = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearHasValue() {
      copyOnWrite();
      instance.clearHasValue();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:opencensus.proto.metrics.v1.LabelValue)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.opencensus.proto.metrics.v1.LabelValue();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "value_",
            "hasValue_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\u0007" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.opencensus.proto.metrics.v1.LabelValue> parser = PARSER;
        if (parser == null) {
          synchronized (io.opencensus.proto.metrics.v1.LabelValue.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.opencensus.proto.metrics.v1.LabelValue>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:opencensus.proto.metrics.v1.LabelValue)
  private static final io.opencensus.proto.metrics.v1.LabelValue DEFAULT_INSTANCE;
  static {
    LabelValue defaultInstance = new LabelValue();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      LabelValue.class, defaultInstance);
  }

  public static io.opencensus.proto.metrics.v1.LabelValue getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<LabelValue> PARSER;

  public static com.google.protobuf.Parser<LabelValue> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

