// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opencensus/proto/metrics/v1/metrics.proto

package io.opencensus.proto.metrics.v1;

/**
 * <pre>
 * The start_timestamp only applies to the count and sum in the SummaryValue.
 * </pre>
 *
 * Protobuf type {@code opencensus.proto.metrics.v1.SummaryValue}
 */
public  final class SummaryValue extends
    com.google.protobuf.GeneratedMessageLite<
        SummaryValue, SummaryValue.Builder> implements
    // @@protoc_insertion_point(message_implements:opencensus.proto.metrics.v1.SummaryValue)
    SummaryValueOrBuilder {
  private SummaryValue() {
  }
  public interface SnapshotOrBuilder extends
      // @@protoc_insertion_point(interface_extends:opencensus.proto.metrics.v1.SummaryValue.Snapshot)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * The number of values in the snapshot. Optional since some systems don't
     * expose this.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value count = 1;</code>
     * @return Whether the count field is set.
     */
    boolean hasCount();
    /**
     * <pre>
     * The number of values in the snapshot. Optional since some systems don't
     * expose this.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value count = 1;</code>
     * @return The count.
     */
    com.google.protobuf.Int64Value getCount();

    /**
     * <pre>
     * The sum of values in the snapshot. Optional since some systems don't
     * expose this. If count is zero then this field must be zero or not set
     * (if not supported).
     * </pre>
     *
     * <code>.google.protobuf.DoubleValue sum = 2;</code>
     * @return Whether the sum field is set.
     */
    boolean hasSum();
    /**
     * <pre>
     * The sum of values in the snapshot. Optional since some systems don't
     * expose this. If count is zero then this field must be zero or not set
     * (if not supported).
     * </pre>
     *
     * <code>.google.protobuf.DoubleValue sum = 2;</code>
     * @return The sum.
     */
    com.google.protobuf.DoubleValue getSum();

    /**
     * <pre>
     * A list of values at different percentiles of the distribution calculated
     * from the current snapshot. The percentiles must be strictly increasing.
     * </pre>
     *
     * <code>repeated .opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile percentile_values = 3;</code>
     */
    java.util.List<io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile> 
        getPercentileValuesList();
    /**
     * <pre>
     * A list of values at different percentiles of the distribution calculated
     * from the current snapshot. The percentiles must be strictly increasing.
     * </pre>
     *
     * <code>repeated .opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile percentile_values = 3;</code>
     */
    io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile getPercentileValues(int index);
    /**
     * <pre>
     * A list of values at different percentiles of the distribution calculated
     * from the current snapshot. The percentiles must be strictly increasing.
     * </pre>
     *
     * <code>repeated .opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile percentile_values = 3;</code>
     */
    int getPercentileValuesCount();
  }
  /**
   * <pre>
   * The values in this message can be reset at arbitrary unknown times, with
   * the requirement that all of them are reset at the same time.
   * </pre>
   *
   * Protobuf type {@code opencensus.proto.metrics.v1.SummaryValue.Snapshot}
   */
  public  static final class Snapshot extends
      com.google.protobuf.GeneratedMessageLite<
          Snapshot, Snapshot.Builder> implements
      // @@protoc_insertion_point(message_implements:opencensus.proto.metrics.v1.SummaryValue.Snapshot)
      SnapshotOrBuilder {
    private Snapshot() {
      percentileValues_ = emptyProtobufList();
    }
    public interface ValueAtPercentileOrBuilder extends
        // @@protoc_insertion_point(interface_extends:opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile)
        com.google.protobuf.MessageLiteOrBuilder {

      /**
       * <pre>
       * The percentile of a distribution. Must be in the interval
       * (0.0, 100.0].
       * </pre>
       *
       * <code>double percentile = 1;</code>
       * @return The percentile.
       */
      double getPercentile();

      /**
       * <pre>
       * The value at the given percentile of a distribution.
       * </pre>
       *
       * <code>double value = 2;</code>
       * @return The value.
       */
      double getValue();
    }
    /**
     * <pre>
     * Represents the value at a given percentile of a distribution.
     * </pre>
     *
     * Protobuf type {@code opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile}
     */
    public  static final class ValueAtPercentile extends
        com.google.protobuf.GeneratedMessageLite<
            ValueAtPercentile, ValueAtPercentile.Builder> implements
        // @@protoc_insertion_point(message_implements:opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile)
        ValueAtPercentileOrBuilder {
      private ValueAtPercentile() {
      }
      public static final int PERCENTILE_FIELD_NUMBER = 1;
      private double percentile_;
      /**
       * <pre>
       * The percentile of a distribution. Must be in the interval
       * (0.0, 100.0].
       * </pre>
       *
       * <code>double percentile = 1;</code>
       * @return The percentile.
       */
      @java.lang.Override
      public double getPercentile() {
        return percentile_;
      }
      /**
       * <pre>
       * The percentile of a distribution. Must be in the interval
       * (0.0, 100.0].
       * </pre>
       *
       * <code>double percentile = 1;</code>
       * @param value The percentile to set.
       */
      private void setPercentile(double value) {
        
        percentile_ = value;
      }
      /**
       * <pre>
       * The percentile of a distribution. Must be in the interval
       * (0.0, 100.0].
       * </pre>
       *
       * <code>double percentile = 1;</code>
       */
      private void clearPercentile() {
        
        percentile_ = 0D;
      }

      public static final int VALUE_FIELD_NUMBER = 2;
      private double value_;
      /**
       * <pre>
       * The value at the given percentile of a distribution.
       * </pre>
       *
       * <code>double value = 2;</code>
       * @return The value.
       */
      @java.lang.Override
      public double getValue() {
        return value_;
      }
      /**
       * <pre>
       * The value at the given percentile of a distribution.
       * </pre>
       *
       * <code>double value = 2;</code>
       * @param value The value to set.
       */
      private void setValue(double value) {
        
        value_ = value;
      }
      /**
       * <pre>
       * The value at the given percentile of a distribution.
       * </pre>
       *
       * <code>double value = 2;</code>
       */
      private void clearValue() {
        
        value_ = 0D;
      }

      public static io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
      }
      public static io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }

      public static Builder newBuilder() {
        return (Builder) DEFAULT_INSTANCE.createBuilder();
      }
      public static Builder newBuilder(io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile prototype) {
        return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
      }

      /**
       * <pre>
       * Represents the value at a given percentile of a distribution.
       * </pre>
       *
       * Protobuf type {@code opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile, Builder> implements
          // @@protoc_insertion_point(builder_implements:opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile)
          io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentileOrBuilder {
        // Construct using io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile.newBuilder()
        private Builder() {
          super(DEFAULT_INSTANCE);
        }


        /**
         * <pre>
         * The percentile of a distribution. Must be in the interval
         * (0.0, 100.0].
         * </pre>
         *
         * <code>double percentile = 1;</code>
         * @return The percentile.
         */
        @java.lang.Override
        public double getPercentile() {
          return instance.getPercentile();
        }
        /**
         * <pre>
         * The percentile of a distribution. Must be in the interval
         * (0.0, 100.0].
         * </pre>
         *
         * <code>double percentile = 1;</code>
         * @param value The percentile to set.
         * @return This builder for chaining.
         */
        public Builder setPercentile(double value) {
          copyOnWrite();
          instance.setPercentile(value);
          return this;
        }
        /**
         * <pre>
         * The percentile of a distribution. Must be in the interval
         * (0.0, 100.0].
         * </pre>
         *
         * <code>double percentile = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearPercentile() {
          copyOnWrite();
          instance.clearPercentile();
          return this;
        }

        /**
         * <pre>
         * The value at the given percentile of a distribution.
         * </pre>
         *
         * <code>double value = 2;</code>
         * @return The value.
         */
        @java.lang.Override
        public double getValue() {
          return instance.getValue();
        }
        /**
         * <pre>
         * The value at the given percentile of a distribution.
         * </pre>
         *
         * <code>double value = 2;</code>
         * @param value The value to set.
         * @return This builder for chaining.
         */
        public Builder setValue(double value) {
          copyOnWrite();
          instance.setValue(value);
          return this;
        }
        /**
         * <pre>
         * The value at the given percentile of a distribution.
         * </pre>
         *
         * <code>double value = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearValue() {
          copyOnWrite();
          instance.clearValue();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile)
      }
      @java.lang.Override
      @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
      protected final java.lang.Object dynamicMethod(
          com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
          java.lang.Object arg0, java.lang.Object arg1) {
        switch (method) {
          case NEW_MUTABLE_INSTANCE: {
            return new io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile();
          }
          case NEW_BUILDER: {
            return new Builder();
          }
          case BUILD_MESSAGE_INFO: {
              java.lang.Object[] objects = new java.lang.Object[] {
                "percentile_",
                "value_",
              };
              java.lang.String info =
                  "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0000\u0002\u0000" +
                  "";
              return newMessageInfo(DEFAULT_INSTANCE, info, objects);
          }
          // fall through
          case GET_DEFAULT_INSTANCE: {
            return DEFAULT_INSTANCE;
          }
          case GET_PARSER: {
            com.google.protobuf.Parser<io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile> parser = PARSER;
            if (parser == null) {
              synchronized (io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile.class) {
                parser = PARSER;
                if (parser == null) {
                  parser =
                      new DefaultInstanceBasedParser<io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile>(
                          DEFAULT_INSTANCE);
                  PARSER = parser;
                }
              }
            }
            return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        case SET_MEMOIZED_IS_INITIALIZED: {
          return null;
        }
        }
        throw new UnsupportedOperationException();
      }


      // @@protoc_insertion_point(class_scope:opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile)
      private static final io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile DEFAULT_INSTANCE;
      static {
        ValueAtPercentile defaultInstance = new ValueAtPercentile();
        // New instances are implicitly immutable so no need to make
        // immutable.
        DEFAULT_INSTANCE = defaultInstance;
        com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
          ValueAtPercentile.class, defaultInstance);
      }

      public static io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static volatile com.google.protobuf.Parser<ValueAtPercentile> PARSER;

      public static com.google.protobuf.Parser<ValueAtPercentile> parser() {
        return DEFAULT_INSTANCE.getParserForType();
      }
    }

    public static final int COUNT_FIELD_NUMBER = 1;
    private com.google.protobuf.Int64Value count_;
    /**
     * <pre>
     * The number of values in the snapshot. Optional since some systems don't
     * expose this.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value count = 1;</code>
     */
    @java.lang.Override
    public boolean hasCount() {
      return count_ != null;
    }
    /**
     * <pre>
     * The number of values in the snapshot. Optional since some systems don't
     * expose this.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value count = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.Int64Value getCount() {
      return count_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : count_;
    }
    /**
     * <pre>
     * The number of values in the snapshot. Optional since some systems don't
     * expose this.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value count = 1;</code>
     */
    private void setCount(com.google.protobuf.Int64Value value) {
      value.getClass();
  count_ = value;
      
      }
    /**
     * <pre>
     * The number of values in the snapshot. Optional since some systems don't
     * expose this.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value count = 1;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeCount(com.google.protobuf.Int64Value value) {
      value.getClass();
  if (count_ != null &&
          count_ != com.google.protobuf.Int64Value.getDefaultInstance()) {
        count_ =
          com.google.protobuf.Int64Value.newBuilder(count_).mergeFrom(value).buildPartial();
      } else {
        count_ = value;
      }
      
    }
    /**
     * <pre>
     * The number of values in the snapshot. Optional since some systems don't
     * expose this.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value count = 1;</code>
     */
    private void clearCount() {  count_ = null;
      
    }

    public static final int SUM_FIELD_NUMBER = 2;
    private com.google.protobuf.DoubleValue sum_;
    /**
     * <pre>
     * The sum of values in the snapshot. Optional since some systems don't
     * expose this. If count is zero then this field must be zero or not set
     * (if not supported).
     * </pre>
     *
     * <code>.google.protobuf.DoubleValue sum = 2;</code>
     */
    @java.lang.Override
    public boolean hasSum() {
      return sum_ != null;
    }
    /**
     * <pre>
     * The sum of values in the snapshot. Optional since some systems don't
     * expose this. If count is zero then this field must be zero or not set
     * (if not supported).
     * </pre>
     *
     * <code>.google.protobuf.DoubleValue sum = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.DoubleValue getSum() {
      return sum_ == null ? com.google.protobuf.DoubleValue.getDefaultInstance() : sum_;
    }
    /**
     * <pre>
     * The sum of values in the snapshot. Optional since some systems don't
     * expose this. If count is zero then this field must be zero or not set
     * (if not supported).
     * </pre>
     *
     * <code>.google.protobuf.DoubleValue sum = 2;</code>
     */
    private void setSum(com.google.protobuf.DoubleValue value) {
      value.getClass();
  sum_ = value;
      
      }
    /**
     * <pre>
     * The sum of values in the snapshot. Optional since some systems don't
     * expose this. If count is zero then this field must be zero or not set
     * (if not supported).
     * </pre>
     *
     * <code>.google.protobuf.DoubleValue sum = 2;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeSum(com.google.protobuf.DoubleValue value) {
      value.getClass();
  if (sum_ != null &&
          sum_ != com.google.protobuf.DoubleValue.getDefaultInstance()) {
        sum_ =
          com.google.protobuf.DoubleValue.newBuilder(sum_).mergeFrom(value).buildPartial();
      } else {
        sum_ = value;
      }
      
    }
    /**
     * <pre>
     * The sum of values in the snapshot. Optional since some systems don't
     * expose this. If count is zero then this field must be zero or not set
     * (if not supported).
     * </pre>
     *
     * <code>.google.protobuf.DoubleValue sum = 2;</code>
     */
    private void clearSum() {  sum_ = null;
      
    }

    public static final int PERCENTILE_VALUES_FIELD_NUMBER = 3;
    private com.google.protobuf.Internal.ProtobufList<io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile> percentileValues_;
    /**
     * <pre>
     * A list of values at different percentiles of the distribution calculated
     * from the current snapshot. The percentiles must be strictly increasing.
     * </pre>
     *
     * <code>repeated .opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile percentile_values = 3;</code>
     */
    @java.lang.Override
    public java.util.List<io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile> getPercentileValuesList() {
      return percentileValues_;
    }
    /**
     * <pre>
     * A list of values at different percentiles of the distribution calculated
     * from the current snapshot. The percentiles must be strictly increasing.
     * </pre>
     *
     * <code>repeated .opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile percentile_values = 3;</code>
     */
    public java.util.List<? extends io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentileOrBuilder> 
        getPercentileValuesOrBuilderList() {
      return percentileValues_;
    }
    /**
     * <pre>
     * A list of values at different percentiles of the distribution calculated
     * from the current snapshot. The percentiles must be strictly increasing.
     * </pre>
     *
     * <code>repeated .opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile percentile_values = 3;</code>
     */
    @java.lang.Override
    public int getPercentileValuesCount() {
      return percentileValues_.size();
    }
    /**
     * <pre>
     * A list of values at different percentiles of the distribution calculated
     * from the current snapshot. The percentiles must be strictly increasing.
     * </pre>
     *
     * <code>repeated .opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile percentile_values = 3;</code>
     */
    @java.lang.Override
    public io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile getPercentileValues(int index) {
      return percentileValues_.get(index);
    }
    /**
     * <pre>
     * A list of values at different percentiles of the distribution calculated
     * from the current snapshot. The percentiles must be strictly increasing.
     * </pre>
     *
     * <code>repeated .opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile percentile_values = 3;</code>
     */
    public io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentileOrBuilder getPercentileValuesOrBuilder(
        int index) {
      return percentileValues_.get(index);
    }
    private void ensurePercentileValuesIsMutable() {
      com.google.protobuf.Internal.ProtobufList<io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile> tmp = percentileValues_;
      if (!tmp.isModifiable()) {
        percentileValues_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <pre>
     * A list of values at different percentiles of the distribution calculated
     * from the current snapshot. The percentiles must be strictly increasing.
     * </pre>
     *
     * <code>repeated .opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile percentile_values = 3;</code>
     */
    private void setPercentileValues(
        int index, io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile value) {
      value.getClass();
  ensurePercentileValuesIsMutable();
      percentileValues_.set(index, value);
    }
    /**
     * <pre>
     * A list of values at different percentiles of the distribution calculated
     * from the current snapshot. The percentiles must be strictly increasing.
     * </pre>
     *
     * <code>repeated .opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile percentile_values = 3;</code>
     */
    private void addPercentileValues(io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile value) {
      value.getClass();
  ensurePercentileValuesIsMutable();
      percentileValues_.add(value);
    }
    /**
     * <pre>
     * A list of values at different percentiles of the distribution calculated
     * from the current snapshot. The percentiles must be strictly increasing.
     * </pre>
     *
     * <code>repeated .opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile percentile_values = 3;</code>
     */
    private void addPercentileValues(
        int index, io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile value) {
      value.getClass();
  ensurePercentileValuesIsMutable();
      percentileValues_.add(index, value);
    }
    /**
     * <pre>
     * A list of values at different percentiles of the distribution calculated
     * from the current snapshot. The percentiles must be strictly increasing.
     * </pre>
     *
     * <code>repeated .opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile percentile_values = 3;</code>
     */
    private void addAllPercentileValues(
        java.lang.Iterable<? extends io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile> values) {
      ensurePercentileValuesIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, percentileValues_);
    }
    /**
     * <pre>
     * A list of values at different percentiles of the distribution calculated
     * from the current snapshot. The percentiles must be strictly increasing.
     * </pre>
     *
     * <code>repeated .opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile percentile_values = 3;</code>
     */
    private void clearPercentileValues() {
      percentileValues_ = emptyProtobufList();
    }
    /**
     * <pre>
     * A list of values at different percentiles of the distribution calculated
     * from the current snapshot. The percentiles must be strictly increasing.
     * </pre>
     *
     * <code>repeated .opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile percentile_values = 3;</code>
     */
    private void removePercentileValues(int index) {
      ensurePercentileValuesIsMutable();
      percentileValues_.remove(index);
    }

    public static io.opencensus.proto.metrics.v1.SummaryValue.Snapshot parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static io.opencensus.proto.metrics.v1.SummaryValue.Snapshot parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static io.opencensus.proto.metrics.v1.SummaryValue.Snapshot parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static io.opencensus.proto.metrics.v1.SummaryValue.Snapshot parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static io.opencensus.proto.metrics.v1.SummaryValue.Snapshot parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static io.opencensus.proto.metrics.v1.SummaryValue.Snapshot parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static io.opencensus.proto.metrics.v1.SummaryValue.Snapshot parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static io.opencensus.proto.metrics.v1.SummaryValue.Snapshot parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static io.opencensus.proto.metrics.v1.SummaryValue.Snapshot parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static io.opencensus.proto.metrics.v1.SummaryValue.Snapshot parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static io.opencensus.proto.metrics.v1.SummaryValue.Snapshot parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static io.opencensus.proto.metrics.v1.SummaryValue.Snapshot parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(io.opencensus.proto.metrics.v1.SummaryValue.Snapshot prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * The values in this message can be reset at arbitrary unknown times, with
     * the requirement that all of them are reset at the same time.
     * </pre>
     *
     * Protobuf type {@code opencensus.proto.metrics.v1.SummaryValue.Snapshot}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          io.opencensus.proto.metrics.v1.SummaryValue.Snapshot, Builder> implements
        // @@protoc_insertion_point(builder_implements:opencensus.proto.metrics.v1.SummaryValue.Snapshot)
        io.opencensus.proto.metrics.v1.SummaryValue.SnapshotOrBuilder {
      // Construct using io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * The number of values in the snapshot. Optional since some systems don't
       * expose this.
       * </pre>
       *
       * <code>.google.protobuf.Int64Value count = 1;</code>
       */
      @java.lang.Override
      public boolean hasCount() {
        return instance.hasCount();
      }
      /**
       * <pre>
       * The number of values in the snapshot. Optional since some systems don't
       * expose this.
       * </pre>
       *
       * <code>.google.protobuf.Int64Value count = 1;</code>
       */
      @java.lang.Override
      public com.google.protobuf.Int64Value getCount() {
        return instance.getCount();
      }
      /**
       * <pre>
       * The number of values in the snapshot. Optional since some systems don't
       * expose this.
       * </pre>
       *
       * <code>.google.protobuf.Int64Value count = 1;</code>
       */
      public Builder setCount(com.google.protobuf.Int64Value value) {
        copyOnWrite();
        instance.setCount(value);
        return this;
        }
      /**
       * <pre>
       * The number of values in the snapshot. Optional since some systems don't
       * expose this.
       * </pre>
       *
       * <code>.google.protobuf.Int64Value count = 1;</code>
       */
      public Builder setCount(
          com.google.protobuf.Int64Value.Builder builderForValue) {
        copyOnWrite();
        instance.setCount(builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * The number of values in the snapshot. Optional since some systems don't
       * expose this.
       * </pre>
       *
       * <code>.google.protobuf.Int64Value count = 1;</code>
       */
      public Builder mergeCount(com.google.protobuf.Int64Value value) {
        copyOnWrite();
        instance.mergeCount(value);
        return this;
      }
      /**
       * <pre>
       * The number of values in the snapshot. Optional since some systems don't
       * expose this.
       * </pre>
       *
       * <code>.google.protobuf.Int64Value count = 1;</code>
       */
      public Builder clearCount() {  copyOnWrite();
        instance.clearCount();
        return this;
      }

      /**
       * <pre>
       * The sum of values in the snapshot. Optional since some systems don't
       * expose this. If count is zero then this field must be zero or not set
       * (if not supported).
       * </pre>
       *
       * <code>.google.protobuf.DoubleValue sum = 2;</code>
       */
      @java.lang.Override
      public boolean hasSum() {
        return instance.hasSum();
      }
      /**
       * <pre>
       * The sum of values in the snapshot. Optional since some systems don't
       * expose this. If count is zero then this field must be zero or not set
       * (if not supported).
       * </pre>
       *
       * <code>.google.protobuf.DoubleValue sum = 2;</code>
       */
      @java.lang.Override
      public com.google.protobuf.DoubleValue getSum() {
        return instance.getSum();
      }
      /**
       * <pre>
       * The sum of values in the snapshot. Optional since some systems don't
       * expose this. If count is zero then this field must be zero or not set
       * (if not supported).
       * </pre>
       *
       * <code>.google.protobuf.DoubleValue sum = 2;</code>
       */
      public Builder setSum(com.google.protobuf.DoubleValue value) {
        copyOnWrite();
        instance.setSum(value);
        return this;
        }
      /**
       * <pre>
       * The sum of values in the snapshot. Optional since some systems don't
       * expose this. If count is zero then this field must be zero or not set
       * (if not supported).
       * </pre>
       *
       * <code>.google.protobuf.DoubleValue sum = 2;</code>
       */
      public Builder setSum(
          com.google.protobuf.DoubleValue.Builder builderForValue) {
        copyOnWrite();
        instance.setSum(builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * The sum of values in the snapshot. Optional since some systems don't
       * expose this. If count is zero then this field must be zero or not set
       * (if not supported).
       * </pre>
       *
       * <code>.google.protobuf.DoubleValue sum = 2;</code>
       */
      public Builder mergeSum(com.google.protobuf.DoubleValue value) {
        copyOnWrite();
        instance.mergeSum(value);
        return this;
      }
      /**
       * <pre>
       * The sum of values in the snapshot. Optional since some systems don't
       * expose this. If count is zero then this field must be zero or not set
       * (if not supported).
       * </pre>
       *
       * <code>.google.protobuf.DoubleValue sum = 2;</code>
       */
      public Builder clearSum() {  copyOnWrite();
        instance.clearSum();
        return this;
      }

      /**
       * <pre>
       * A list of values at different percentiles of the distribution calculated
       * from the current snapshot. The percentiles must be strictly increasing.
       * </pre>
       *
       * <code>repeated .opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile percentile_values = 3;</code>
       */
      @java.lang.Override
      public java.util.List<io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile> getPercentileValuesList() {
        return java.util.Collections.unmodifiableList(
            instance.getPercentileValuesList());
      }
      /**
       * <pre>
       * A list of values at different percentiles of the distribution calculated
       * from the current snapshot. The percentiles must be strictly increasing.
       * </pre>
       *
       * <code>repeated .opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile percentile_values = 3;</code>
       */
      @java.lang.Override
      public int getPercentileValuesCount() {
        return instance.getPercentileValuesCount();
      }/**
       * <pre>
       * A list of values at different percentiles of the distribution calculated
       * from the current snapshot. The percentiles must be strictly increasing.
       * </pre>
       *
       * <code>repeated .opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile percentile_values = 3;</code>
       */
      @java.lang.Override
      public io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile getPercentileValues(int index) {
        return instance.getPercentileValues(index);
      }
      /**
       * <pre>
       * A list of values at different percentiles of the distribution calculated
       * from the current snapshot. The percentiles must be strictly increasing.
       * </pre>
       *
       * <code>repeated .opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile percentile_values = 3;</code>
       */
      public Builder setPercentileValues(
          int index, io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile value) {
        copyOnWrite();
        instance.setPercentileValues(index, value);
        return this;
      }
      /**
       * <pre>
       * A list of values at different percentiles of the distribution calculated
       * from the current snapshot. The percentiles must be strictly increasing.
       * </pre>
       *
       * <code>repeated .opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile percentile_values = 3;</code>
       */
      public Builder setPercentileValues(
          int index, io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile.Builder builderForValue) {
        copyOnWrite();
        instance.setPercentileValues(index,
            builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * A list of values at different percentiles of the distribution calculated
       * from the current snapshot. The percentiles must be strictly increasing.
       * </pre>
       *
       * <code>repeated .opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile percentile_values = 3;</code>
       */
      public Builder addPercentileValues(io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile value) {
        copyOnWrite();
        instance.addPercentileValues(value);
        return this;
      }
      /**
       * <pre>
       * A list of values at different percentiles of the distribution calculated
       * from the current snapshot. The percentiles must be strictly increasing.
       * </pre>
       *
       * <code>repeated .opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile percentile_values = 3;</code>
       */
      public Builder addPercentileValues(
          int index, io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile value) {
        copyOnWrite();
        instance.addPercentileValues(index, value);
        return this;
      }
      /**
       * <pre>
       * A list of values at different percentiles of the distribution calculated
       * from the current snapshot. The percentiles must be strictly increasing.
       * </pre>
       *
       * <code>repeated .opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile percentile_values = 3;</code>
       */
      public Builder addPercentileValues(
          io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile.Builder builderForValue) {
        copyOnWrite();
        instance.addPercentileValues(builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * A list of values at different percentiles of the distribution calculated
       * from the current snapshot. The percentiles must be strictly increasing.
       * </pre>
       *
       * <code>repeated .opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile percentile_values = 3;</code>
       */
      public Builder addPercentileValues(
          int index, io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile.Builder builderForValue) {
        copyOnWrite();
        instance.addPercentileValues(index,
            builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * A list of values at different percentiles of the distribution calculated
       * from the current snapshot. The percentiles must be strictly increasing.
       * </pre>
       *
       * <code>repeated .opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile percentile_values = 3;</code>
       */
      public Builder addAllPercentileValues(
          java.lang.Iterable<? extends io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile> values) {
        copyOnWrite();
        instance.addAllPercentileValues(values);
        return this;
      }
      /**
       * <pre>
       * A list of values at different percentiles of the distribution calculated
       * from the current snapshot. The percentiles must be strictly increasing.
       * </pre>
       *
       * <code>repeated .opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile percentile_values = 3;</code>
       */
      public Builder clearPercentileValues() {
        copyOnWrite();
        instance.clearPercentileValues();
        return this;
      }
      /**
       * <pre>
       * A list of values at different percentiles of the distribution calculated
       * from the current snapshot. The percentiles must be strictly increasing.
       * </pre>
       *
       * <code>repeated .opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile percentile_values = 3;</code>
       */
      public Builder removePercentileValues(int index) {
        copyOnWrite();
        instance.removePercentileValues(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:opencensus.proto.metrics.v1.SummaryValue.Snapshot)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new io.opencensus.proto.metrics.v1.SummaryValue.Snapshot();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "count_",
              "sum_",
              "percentileValues_",
              io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile.class,
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0001\u0000\u0001\t\u0002\t\u0003" +
                "\u001b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<io.opencensus.proto.metrics.v1.SummaryValue.Snapshot> parser = PARSER;
          if (parser == null) {
            synchronized (io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<io.opencensus.proto.metrics.v1.SummaryValue.Snapshot>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:opencensus.proto.metrics.v1.SummaryValue.Snapshot)
    private static final io.opencensus.proto.metrics.v1.SummaryValue.Snapshot DEFAULT_INSTANCE;
    static {
      Snapshot defaultInstance = new Snapshot();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Snapshot.class, defaultInstance);
    }

    public static io.opencensus.proto.metrics.v1.SummaryValue.Snapshot getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Snapshot> PARSER;

    public static com.google.protobuf.Parser<Snapshot> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public static final int COUNT_FIELD_NUMBER = 1;
  private com.google.protobuf.Int64Value count_;
  /**
   * <pre>
   * The total number of recorded values since start_time. Optional since
   * some systems don't expose this.
   * </pre>
   *
   * <code>.google.protobuf.Int64Value count = 1;</code>
   */
  @java.lang.Override
  public boolean hasCount() {
    return count_ != null;
  }
  /**
   * <pre>
   * The total number of recorded values since start_time. Optional since
   * some systems don't expose this.
   * </pre>
   *
   * <code>.google.protobuf.Int64Value count = 1;</code>
   */
  @java.lang.Override
  public com.google.protobuf.Int64Value getCount() {
    return count_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : count_;
  }
  /**
   * <pre>
   * The total number of recorded values since start_time. Optional since
   * some systems don't expose this.
   * </pre>
   *
   * <code>.google.protobuf.Int64Value count = 1;</code>
   */
  private void setCount(com.google.protobuf.Int64Value value) {
    value.getClass();
  count_ = value;
    
    }
  /**
   * <pre>
   * The total number of recorded values since start_time. Optional since
   * some systems don't expose this.
   * </pre>
   *
   * <code>.google.protobuf.Int64Value count = 1;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeCount(com.google.protobuf.Int64Value value) {
    value.getClass();
  if (count_ != null &&
        count_ != com.google.protobuf.Int64Value.getDefaultInstance()) {
      count_ =
        com.google.protobuf.Int64Value.newBuilder(count_).mergeFrom(value).buildPartial();
    } else {
      count_ = value;
    }
    
  }
  /**
   * <pre>
   * The total number of recorded values since start_time. Optional since
   * some systems don't expose this.
   * </pre>
   *
   * <code>.google.protobuf.Int64Value count = 1;</code>
   */
  private void clearCount() {  count_ = null;
    
  }

  public static final int SUM_FIELD_NUMBER = 2;
  private com.google.protobuf.DoubleValue sum_;
  /**
   * <pre>
   * The total sum of recorded values since start_time. Optional since some
   * systems don't expose this. If count is zero then this field must be zero.
   * This field must be unset if the sum is not available.
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue sum = 2;</code>
   */
  @java.lang.Override
  public boolean hasSum() {
    return sum_ != null;
  }
  /**
   * <pre>
   * The total sum of recorded values since start_time. Optional since some
   * systems don't expose this. If count is zero then this field must be zero.
   * This field must be unset if the sum is not available.
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue sum = 2;</code>
   */
  @java.lang.Override
  public com.google.protobuf.DoubleValue getSum() {
    return sum_ == null ? com.google.protobuf.DoubleValue.getDefaultInstance() : sum_;
  }
  /**
   * <pre>
   * The total sum of recorded values since start_time. Optional since some
   * systems don't expose this. If count is zero then this field must be zero.
   * This field must be unset if the sum is not available.
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue sum = 2;</code>
   */
  private void setSum(com.google.protobuf.DoubleValue value) {
    value.getClass();
  sum_ = value;
    
    }
  /**
   * <pre>
   * The total sum of recorded values since start_time. Optional since some
   * systems don't expose this. If count is zero then this field must be zero.
   * This field must be unset if the sum is not available.
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue sum = 2;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeSum(com.google.protobuf.DoubleValue value) {
    value.getClass();
  if (sum_ != null &&
        sum_ != com.google.protobuf.DoubleValue.getDefaultInstance()) {
      sum_ =
        com.google.protobuf.DoubleValue.newBuilder(sum_).mergeFrom(value).buildPartial();
    } else {
      sum_ = value;
    }
    
  }
  /**
   * <pre>
   * The total sum of recorded values since start_time. Optional since some
   * systems don't expose this. If count is zero then this field must be zero.
   * This field must be unset if the sum is not available.
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue sum = 2;</code>
   */
  private void clearSum() {  sum_ = null;
    
  }

  public static final int SNAPSHOT_FIELD_NUMBER = 3;
  private io.opencensus.proto.metrics.v1.SummaryValue.Snapshot snapshot_;
  /**
   * <pre>
   * Values calculated over an arbitrary time window.
   * </pre>
   *
   * <code>.opencensus.proto.metrics.v1.SummaryValue.Snapshot snapshot = 3;</code>
   */
  @java.lang.Override
  public boolean hasSnapshot() {
    return snapshot_ != null;
  }
  /**
   * <pre>
   * Values calculated over an arbitrary time window.
   * </pre>
   *
   * <code>.opencensus.proto.metrics.v1.SummaryValue.Snapshot snapshot = 3;</code>
   */
  @java.lang.Override
  public io.opencensus.proto.metrics.v1.SummaryValue.Snapshot getSnapshot() {
    return snapshot_ == null ? io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.getDefaultInstance() : snapshot_;
  }
  /**
   * <pre>
   * Values calculated over an arbitrary time window.
   * </pre>
   *
   * <code>.opencensus.proto.metrics.v1.SummaryValue.Snapshot snapshot = 3;</code>
   */
  private void setSnapshot(io.opencensus.proto.metrics.v1.SummaryValue.Snapshot value) {
    value.getClass();
  snapshot_ = value;
    
    }
  /**
   * <pre>
   * Values calculated over an arbitrary time window.
   * </pre>
   *
   * <code>.opencensus.proto.metrics.v1.SummaryValue.Snapshot snapshot = 3;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeSnapshot(io.opencensus.proto.metrics.v1.SummaryValue.Snapshot value) {
    value.getClass();
  if (snapshot_ != null &&
        snapshot_ != io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.getDefaultInstance()) {
      snapshot_ =
        io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.newBuilder(snapshot_).mergeFrom(value).buildPartial();
    } else {
      snapshot_ = value;
    }
    
  }
  /**
   * <pre>
   * Values calculated over an arbitrary time window.
   * </pre>
   *
   * <code>.opencensus.proto.metrics.v1.SummaryValue.Snapshot snapshot = 3;</code>
   */
  private void clearSnapshot() {  snapshot_ = null;
    
  }

  public static io.opencensus.proto.metrics.v1.SummaryValue parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.opencensus.proto.metrics.v1.SummaryValue parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.opencensus.proto.metrics.v1.SummaryValue parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.opencensus.proto.metrics.v1.SummaryValue parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.opencensus.proto.metrics.v1.SummaryValue parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.opencensus.proto.metrics.v1.SummaryValue parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.opencensus.proto.metrics.v1.SummaryValue parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.opencensus.proto.metrics.v1.SummaryValue parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.opencensus.proto.metrics.v1.SummaryValue parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static io.opencensus.proto.metrics.v1.SummaryValue parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.opencensus.proto.metrics.v1.SummaryValue parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.opencensus.proto.metrics.v1.SummaryValue parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.opencensus.proto.metrics.v1.SummaryValue prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * The start_timestamp only applies to the count and sum in the SummaryValue.
   * </pre>
   *
   * Protobuf type {@code opencensus.proto.metrics.v1.SummaryValue}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.opencensus.proto.metrics.v1.SummaryValue, Builder> implements
      // @@protoc_insertion_point(builder_implements:opencensus.proto.metrics.v1.SummaryValue)
      io.opencensus.proto.metrics.v1.SummaryValueOrBuilder {
    // Construct using io.opencensus.proto.metrics.v1.SummaryValue.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * The total number of recorded values since start_time. Optional since
     * some systems don't expose this.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value count = 1;</code>
     */
    @java.lang.Override
    public boolean hasCount() {
      return instance.hasCount();
    }
    /**
     * <pre>
     * The total number of recorded values since start_time. Optional since
     * some systems don't expose this.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value count = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.Int64Value getCount() {
      return instance.getCount();
    }
    /**
     * <pre>
     * The total number of recorded values since start_time. Optional since
     * some systems don't expose this.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value count = 1;</code>
     */
    public Builder setCount(com.google.protobuf.Int64Value value) {
      copyOnWrite();
      instance.setCount(value);
      return this;
      }
    /**
     * <pre>
     * The total number of recorded values since start_time. Optional since
     * some systems don't expose this.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value count = 1;</code>
     */
    public Builder setCount(
        com.google.protobuf.Int64Value.Builder builderForValue) {
      copyOnWrite();
      instance.setCount(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * The total number of recorded values since start_time. Optional since
     * some systems don't expose this.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value count = 1;</code>
     */
    public Builder mergeCount(com.google.protobuf.Int64Value value) {
      copyOnWrite();
      instance.mergeCount(value);
      return this;
    }
    /**
     * <pre>
     * The total number of recorded values since start_time. Optional since
     * some systems don't expose this.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value count = 1;</code>
     */
    public Builder clearCount() {  copyOnWrite();
      instance.clearCount();
      return this;
    }

    /**
     * <pre>
     * The total sum of recorded values since start_time. Optional since some
     * systems don't expose this. If count is zero then this field must be zero.
     * This field must be unset if the sum is not available.
     * </pre>
     *
     * <code>.google.protobuf.DoubleValue sum = 2;</code>
     */
    @java.lang.Override
    public boolean hasSum() {
      return instance.hasSum();
    }
    /**
     * <pre>
     * The total sum of recorded values since start_time. Optional since some
     * systems don't expose this. If count is zero then this field must be zero.
     * This field must be unset if the sum is not available.
     * </pre>
     *
     * <code>.google.protobuf.DoubleValue sum = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.DoubleValue getSum() {
      return instance.getSum();
    }
    /**
     * <pre>
     * The total sum of recorded values since start_time. Optional since some
     * systems don't expose this. If count is zero then this field must be zero.
     * This field must be unset if the sum is not available.
     * </pre>
     *
     * <code>.google.protobuf.DoubleValue sum = 2;</code>
     */
    public Builder setSum(com.google.protobuf.DoubleValue value) {
      copyOnWrite();
      instance.setSum(value);
      return this;
      }
    /**
     * <pre>
     * The total sum of recorded values since start_time. Optional since some
     * systems don't expose this. If count is zero then this field must be zero.
     * This field must be unset if the sum is not available.
     * </pre>
     *
     * <code>.google.protobuf.DoubleValue sum = 2;</code>
     */
    public Builder setSum(
        com.google.protobuf.DoubleValue.Builder builderForValue) {
      copyOnWrite();
      instance.setSum(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * The total sum of recorded values since start_time. Optional since some
     * systems don't expose this. If count is zero then this field must be zero.
     * This field must be unset if the sum is not available.
     * </pre>
     *
     * <code>.google.protobuf.DoubleValue sum = 2;</code>
     */
    public Builder mergeSum(com.google.protobuf.DoubleValue value) {
      copyOnWrite();
      instance.mergeSum(value);
      return this;
    }
    /**
     * <pre>
     * The total sum of recorded values since start_time. Optional since some
     * systems don't expose this. If count is zero then this field must be zero.
     * This field must be unset if the sum is not available.
     * </pre>
     *
     * <code>.google.protobuf.DoubleValue sum = 2;</code>
     */
    public Builder clearSum() {  copyOnWrite();
      instance.clearSum();
      return this;
    }

    /**
     * <pre>
     * Values calculated over an arbitrary time window.
     * </pre>
     *
     * <code>.opencensus.proto.metrics.v1.SummaryValue.Snapshot snapshot = 3;</code>
     */
    @java.lang.Override
    public boolean hasSnapshot() {
      return instance.hasSnapshot();
    }
    /**
     * <pre>
     * Values calculated over an arbitrary time window.
     * </pre>
     *
     * <code>.opencensus.proto.metrics.v1.SummaryValue.Snapshot snapshot = 3;</code>
     */
    @java.lang.Override
    public io.opencensus.proto.metrics.v1.SummaryValue.Snapshot getSnapshot() {
      return instance.getSnapshot();
    }
    /**
     * <pre>
     * Values calculated over an arbitrary time window.
     * </pre>
     *
     * <code>.opencensus.proto.metrics.v1.SummaryValue.Snapshot snapshot = 3;</code>
     */
    public Builder setSnapshot(io.opencensus.proto.metrics.v1.SummaryValue.Snapshot value) {
      copyOnWrite();
      instance.setSnapshot(value);
      return this;
      }
    /**
     * <pre>
     * Values calculated over an arbitrary time window.
     * </pre>
     *
     * <code>.opencensus.proto.metrics.v1.SummaryValue.Snapshot snapshot = 3;</code>
     */
    public Builder setSnapshot(
        io.opencensus.proto.metrics.v1.SummaryValue.Snapshot.Builder builderForValue) {
      copyOnWrite();
      instance.setSnapshot(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * Values calculated over an arbitrary time window.
     * </pre>
     *
     * <code>.opencensus.proto.metrics.v1.SummaryValue.Snapshot snapshot = 3;</code>
     */
    public Builder mergeSnapshot(io.opencensus.proto.metrics.v1.SummaryValue.Snapshot value) {
      copyOnWrite();
      instance.mergeSnapshot(value);
      return this;
    }
    /**
     * <pre>
     * Values calculated over an arbitrary time window.
     * </pre>
     *
     * <code>.opencensus.proto.metrics.v1.SummaryValue.Snapshot snapshot = 3;</code>
     */
    public Builder clearSnapshot() {  copyOnWrite();
      instance.clearSnapshot();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:opencensus.proto.metrics.v1.SummaryValue)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.opencensus.proto.metrics.v1.SummaryValue();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "count_",
            "sum_",
            "snapshot_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\t\u0002\t\u0003" +
              "\t";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.opencensus.proto.metrics.v1.SummaryValue> parser = PARSER;
        if (parser == null) {
          synchronized (io.opencensus.proto.metrics.v1.SummaryValue.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.opencensus.proto.metrics.v1.SummaryValue>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:opencensus.proto.metrics.v1.SummaryValue)
  private static final io.opencensus.proto.metrics.v1.SummaryValue DEFAULT_INSTANCE;
  static {
    SummaryValue defaultInstance = new SummaryValue();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      SummaryValue.class, defaultInstance);
  }

  public static io.opencensus.proto.metrics.v1.SummaryValue getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<SummaryValue> PARSER;

  public static com.google.protobuf.Parser<SummaryValue> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

