// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opencensus/proto/trace/v1/trace_config.proto

package io.opencensus.proto.trace.v1;

/**
 * <pre>
 * Sampler that tries to uniformly sample traces with a given probability.
 * The probability of sampling a trace is equal to that of the specified probability.
 * </pre>
 *
 * Protobuf type {@code opencensus.proto.trace.v1.ProbabilitySampler}
 */
public  final class ProbabilitySampler extends
    com.google.protobuf.GeneratedMessageLite<
        ProbabilitySampler, ProbabilitySampler.Builder> implements
    // @@protoc_insertion_point(message_implements:opencensus.proto.trace.v1.ProbabilitySampler)
    ProbabilitySamplerOrBuilder {
  private ProbabilitySampler() {
  }
  public static final int SAMPLINGPROBABILITY_FIELD_NUMBER = 1;
  private double samplingProbability_;
  /**
   * <pre>
   * The desired probability of sampling. Must be within [0.0, 1.0].
   * </pre>
   *
   * <code>double samplingProbability = 1;</code>
   * @return The samplingProbability.
   */
  @java.lang.Override
  public double getSamplingProbability() {
    return samplingProbability_;
  }
  /**
   * <pre>
   * The desired probability of sampling. Must be within [0.0, 1.0].
   * </pre>
   *
   * <code>double samplingProbability = 1;</code>
   * @param value The samplingProbability to set.
   */
  private void setSamplingProbability(double value) {
    
    samplingProbability_ = value;
  }
  /**
   * <pre>
   * The desired probability of sampling. Must be within [0.0, 1.0].
   * </pre>
   *
   * <code>double samplingProbability = 1;</code>
   */
  private void clearSamplingProbability() {
    
    samplingProbability_ = 0D;
  }

  public static io.opencensus.proto.trace.v1.ProbabilitySampler parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.opencensus.proto.trace.v1.ProbabilitySampler parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.opencensus.proto.trace.v1.ProbabilitySampler parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.opencensus.proto.trace.v1.ProbabilitySampler parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.opencensus.proto.trace.v1.ProbabilitySampler parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.opencensus.proto.trace.v1.ProbabilitySampler parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.opencensus.proto.trace.v1.ProbabilitySampler parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.opencensus.proto.trace.v1.ProbabilitySampler parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.opencensus.proto.trace.v1.ProbabilitySampler parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static io.opencensus.proto.trace.v1.ProbabilitySampler parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.opencensus.proto.trace.v1.ProbabilitySampler parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.opencensus.proto.trace.v1.ProbabilitySampler parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.opencensus.proto.trace.v1.ProbabilitySampler prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Sampler that tries to uniformly sample traces with a given probability.
   * The probability of sampling a trace is equal to that of the specified probability.
   * </pre>
   *
   * Protobuf type {@code opencensus.proto.trace.v1.ProbabilitySampler}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.opencensus.proto.trace.v1.ProbabilitySampler, Builder> implements
      // @@protoc_insertion_point(builder_implements:opencensus.proto.trace.v1.ProbabilitySampler)
      io.opencensus.proto.trace.v1.ProbabilitySamplerOrBuilder {
    // Construct using io.opencensus.proto.trace.v1.ProbabilitySampler.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * The desired probability of sampling. Must be within [0.0, 1.0].
     * </pre>
     *
     * <code>double samplingProbability = 1;</code>
     * @return The samplingProbability.
     */
    @java.lang.Override
    public double getSamplingProbability() {
      return instance.getSamplingProbability();
    }
    /**
     * <pre>
     * The desired probability of sampling. Must be within [0.0, 1.0].
     * </pre>
     *
     * <code>double samplingProbability = 1;</code>
     * @param value The samplingProbability to set.
     * @return This builder for chaining.
     */
    public Builder setSamplingProbability(double value) {
      copyOnWrite();
      instance.setSamplingProbability(value);
      return this;
    }
    /**
     * <pre>
     * The desired probability of sampling. Must be within [0.0, 1.0].
     * </pre>
     *
     * <code>double samplingProbability = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSamplingProbability() {
      copyOnWrite();
      instance.clearSamplingProbability();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:opencensus.proto.trace.v1.ProbabilitySampler)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.opencensus.proto.trace.v1.ProbabilitySampler();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "samplingProbability_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.opencensus.proto.trace.v1.ProbabilitySampler> parser = PARSER;
        if (parser == null) {
          synchronized (io.opencensus.proto.trace.v1.ProbabilitySampler.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.opencensus.proto.trace.v1.ProbabilitySampler>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:opencensus.proto.trace.v1.ProbabilitySampler)
  private static final io.opencensus.proto.trace.v1.ProbabilitySampler DEFAULT_INSTANCE;
  static {
    ProbabilitySampler defaultInstance = new ProbabilitySampler();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ProbabilitySampler.class, defaultInstance);
  }

  public static io.opencensus.proto.trace.v1.ProbabilitySampler getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ProbabilitySampler> PARSER;

  public static com.google.protobuf.Parser<ProbabilitySampler> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

